---
title: Project Review Template 
author: Pooja Gokhale
date: date-modified
format: 
  html:
    toc: true
    toc-depth: 3
    number-sections: true
---

# Overview

Title of project: Investigating the incidence and potential risk factors for hypertension-related mortalities in adults in the United States.

Name of project author(s): Shaun van den Hurk

Name of project reviewer: Pooja Gokhale


# Specific project content evaluation
## Background, Context and Motivation

### Feedback and Comments
The background information is comprehensive. There are a few grammatical mistakes and the general writing could be slightly improved.
The aims and hypotheses are well stated.
The references are not cited appropriately - (..1..) - they appear in this way in the manuscript.
Additionally, in the data source, the citations seem to have been added manually. These should be removed.

### Summary assessment
* strong contextualization and motivation


## Question description
### Feedback and Comments
The question and hypotheses are stated clearly. The data source is directly related to the question.

### Summary assessment
* question/hypotheses fully clear


## Data description
### Feedback and Comments
The data source is provided clearly. There is no codebook. It would be helpful to mention all the variables available in the dataset.

### Summary assessment
* source and overall structure of data somewhat explained


## Data wrangling and exploratory analysis
How well is the data cleaned/processed and explored? Are all steps reasonable and well explained? Are alternatives discussed and considered? Are meaningful exploratory results shown (e.g. in the supplementary materials)?

### Feedback and Comments
The data cleaning process has been mentioned in adequate detail. 
The steps are reasonable and well explained.
Alternative methods have not been discussed, however the methods used are appropriate.
The exploratory figures have also been given.
The metadata for the figures does not seem necessary and could be removed.

### Summary assessment
* essentially no weaknesses in wrangling and exploratory component


## Appropriateness of Analysis
### Feedback and Comments
The analysis methods were appropriate. The analysis was done correctly. 

### Summary assessment
* strong and reasonable analysis

## Presentation
### Feedback and Comments
The figures and tables are generally good quality. However, the figures have meta-data included. 

### Summary assessment
* results are presented ok, with room for improvement


## Discussion/Conclusions
### Feedback and Comments
The discussion is very well written. Reference numbers have been given but there are no references. 

### Summary assessment
* minor parts wrong, missing or unclear


## Further comments

Make sure the references are cited correctly. Remove meta-data from the figures.


# Overall project content evaluation

## Structure
### Feedback and Comments
The project is well-structured. The reference file has not been updated. There are a few irrelevant files in the assets folder.

### Summary assessment
* mostly clear, but some confusing parts (e.g. useless files, things in the wrong folders)

## Documentation 
### Feedback and Comments
The code files are very well documented and explained.

### Summary assessment
* fully and well documented


## Reproducibility
### Feedback and Comments
The code files run without issues. The code works when the code chunks are run, however does not render as an html document. This may be related to issues with computational power and storage.

### Summary assessment
* small parts not reproducible or required manual intervention


## Thoroughness
### Feedback and Comments
The overall study is extremely thorough. All parts have been discussed well. Most of the issues are related to documentation, not the actual analysis.

### Summary assessment
* strong level of thorougness


## Further comments
Here are my suggestions:
1. Add references.
2. Ensure that all code files render properly.
3. Remove meta-data from figures.
4. General writing improvement (minor).





